#!/usr/bin/env python3
import os
import sys
import argparse
import json

import cv2
import numpy as np
import matplotlib.pyplot as plt


def parse_args():
    parser = argparse.ArgumentParser(
        description="Processing images in a folder and generating an SQL file with features."
    )
    parser.add_argument(
        "folder",
        help="Path to the folder with images (.jpg/.jpeg/.png)"
    )
    return parser.parse_args()


def is_image_file(filename):
    ext = os.path.splitext(filename)[1].lower()
    return ext in [".jpg", ".jpeg", ".png"]


def escape_sql(value: str) -> str:
    """
    Escape single quotes for SQL string: ' -> ''.
    """
    return value.replace("'", "''")


def process_image(image_path, output_dirs):
    # Load image
    img = cv2.imread(image_path)
    if img is None:
        print(f"[WARN] Could not load file as image: {image_path}")
        return None

    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # width, height
    height, width = gray.shape

    # Edges (Canny)
    edges = cv2.Canny(gray, 100, 200)

    # Corners (Shi-Tomasi)
    corners_img = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)  # to draw colored points
    corners = cv2.goodFeaturesToTrack(
        gray,
        maxCorners=200,
        qualityLevel=0.01,
        minDistance=10
    )
    if corners is not None:
        corners = corners.astype(int)
        for c in corners:
            x, y = c.ravel()
            cv2.circle(corners_img, (x, y), 3, (0, 0, 255), -1)  # red points

    # Grayscale intensity histogram (256 bins)
    hist = cv2.calcHist([gray], [0], None, [256], [0, 256])
    hist = hist.flatten()  # make it a 1D array

    # Preparing file names
    base_name = os.path.splitext(os.path.basename(image_path))[0]

    gray_path = os.path.join(output_dirs["grayscale"], f"{base_name}_gray.png")
    edges_path = os.path.join(output_dirs["edges"], f"{base_name}_edges.png")
    corners_path = os.path.join(output_dirs["corners"], f"{base_name}_corners.png")
    hist_img_path = os.path.join(output_dirs["histograms"], f"{base_name}_hist.png")

    # Saving imges
    cv2.imwrite(gray_path, gray)
    cv2.imwrite(edges_path, edges)
    cv2.imwrite(corners_path, corners_img)

    # Visualize histogram w/ matplotlib
    plt.figure()
    plt.title(f"Grayscale Histogram - {base_name}")
    plt.xlabel("Intensity value (0-255)")
    plt.ylabel("Pixel count")
    plt.plot(hist)
    plt.xlim([0, 255])
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(hist_img_path)
    plt.close()

    # Convert histogram to JSON (list of numbers)
    hist_list = hist.astype(float).tolist()
    hist_json = json.dumps(hist_list, ensure_ascii=False)

    # Collect all features into a dictionary
    features = {
        "image_path": os.path.abspath(image_path),
        "width": width,
        "height": height,
        "histogram_json": hist_json,
        "gray_path": os.path.abspath(gray_path),
        "edges_path": os.path.abspath(edges_path),
        "corners_path": os.path.abspath(corners_path),
        "hist_img_path": os.path.abspath(hist_img_path),
    }

    return features


def generate_sql(records, sql_path, table_name="image_features"):
    lines = []

    # Dropping the table if it exists
    lines.append(f"IF OBJECT_ID('{table_name}', 'U') IS NOT NULL")
    lines.append(f"    DROP TABLE {table_name};")
    lines.append("")

    # Creating table for MS SQL
    lines.append(f"CREATE TABLE {table_name} (")
    lines.append("    id INT IDENTITY(1,1) PRIMARY KEY,")
    lines.append("    image_path NVARCHAR(1024) NOT NULL,")
    lines.append("    width INT NOT NULL,")
    lines.append("    height INT NOT NULL,")
    lines.append("    histogram_values NVARCHAR(MAX) NOT NULL,")
    lines.append("    grayscale_path NVARCHAR(1024) NOT NULL,")
    lines.append("    edges_path NVARCHAR(1024) NOT NULL,")
    lines.append("    corners_path NVARCHAR(1024) NOT NULL,")
    lines.append("    histogram_image_path NVARCHAR(1024) NOT NULL")
    lines.append(");")
    lines.append("")

    # INSERTs (without id — it will be generated by IDENTITY)
    for rec in records:
        image_path = escape_sql(rec["image_path"])
        width = rec["width"]
        height = rec["height"]
        histogram_values = escape_sql(rec["histogram_json"])
        gray_path = escape_sql(rec["gray_path"])
        edges_path = escape_sql(rec["edges_path"])
        corners_path = escape_sql(rec["corners_path"])
        hist_img_path = escape_sql(rec["hist_img_path"])

        insert = (
            f"INSERT INTO {table_name} "
            f"(image_path, width, height, histogram_values, "
            f"grayscale_path, edges_path, corners_path, histogram_image_path) "
            f"VALUES ("
            f"'{image_path}', "
            f"{width}, "
            f"{height}, "
            f"'{histogram_values}', "
            f"'{gray_path}', "
            f"'{edges_path}', "
            f"'{corners_path}', "
            f"'{hist_img_path}'"
            f");"
        )
        lines.append(insert)

    with open(sql_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[INFO] SQL-файл сгенерирован: {sql_path}")

def main():
    args = parse_args()
    input_folder = args.folder

    if not os.path.isdir(input_folder):
        print(f"[ERROR] Папка не существует: {input_folder}")
        sys.exit(1)

    # Create output folder inside the input folder
    output_root = os.path.join(input_folder, "output")
    os.makedirs(output_root, exist_ok=True)

    # Subfolders for different image types
    output_dirs = {
        "grayscale": os.path.join(output_root, "grayscale"),
        "edges": os.path.join(output_root, "edges"),
        "corners": os.path.join(output_root, "corners"),
        "histograms": os.path.join(output_root, "histograms"),
    }

    for d in output_dirs.values():
        os.makedirs(d, exist_ok=True)

    records = []

    # Iterate over all files in the folder (non-recursive, can be extended if needed)
    for filename in os.listdir(input_folder):
        full_path = os.path.join(input_folder, filename)

        if not os.path.isfile(full_path):
            continue

        if not is_image_file(filename):
            continue

        print(f"[INFO] Processing image: {full_path}")
        features = process_image(full_path, output_dirs)
        if features is not None:
            records.append(features)

    if not records:
        print("[WARN] No suitable images (.jpg/.jpeg/.png) were found. The SQL file will not be created.")
        sys.exit(0)

    # SQL generation
    sql_path = os.path.join(output_root, "image_features.sql")
    generate_sql(records, sql_path)

    print("[INFO] Done")


if __name__ == "__main__":
    main()